### ISSUE TITLE
Factored out `self_replace` from rustup

### ISSUE THREAD

**Issue by simonsan** [jaemk/self_update#109]
Can be found here: https://docs.rs/self-replace/latest/self_replace/

Maybe it would be nice to share that code within `self_update`?

**Comment by mitsuhiko** [comment]
I was looking into this. The benefit would be that currently this crate leaves leftovers behind after the update: https://github.com/jaemk/self_update/blob/1a507bb4cd687d14e044dce8b7b2d66846ea581c/src/update.rs#L147-L150
