### ISSUE TITLE
Gitlab Support?

### ISSUE THREAD

**Issue by brycefisher** [jaemk/self_update#31]
I'd love to use this with Gitlab. How difficult would it be to support a new backend? Would you be interested in a contribution for this feature?

**Comment by jaemk** [comment]
I'm not very familiar with gitlab's release api. If it's anything like github's, then most of it could be copied! Contributions are welcomed!

**Comment by brycefisher** [comment]
I started poking at this and the two APIs are largely similar AFAICT, but Github API has a lot more metadata available (ex: content-type). I think if we're opinionated about how to use the Gitlab, it _should_ work. I'll dig a little deeper to validate that the same general process for Github API will work, but I'm cautiously optimistic right now

**Comment by Silveress** [comment]
Did either of you have any luck figuring out a solution?

**Comment by brycefisher** [comment]
Not yet! But it looks to be very possible based an hour of squinting at the two APIs and this library.

**Comment by jaemk** [comment]
released support in 0.17.0, see #53
