### ISSUE TITLE
AWS S3 support

### ISSUE THREAD

**Issue by bochaco** [jaemk/self_update#34]
This is a proposal to support S3 as a backend in this crate. I'm working on a first implementation of such a backend and was wondering if this is something you'd agree to have and when ready release with self-update crate?

I'm doing this as part of task for some binaries where we use this crate from (I'm working on https://github.com/maidsafe project), and we publish some releases on S3, therefore I was planning to send it as a PR in the next few days if that's something you'll consider for this crate.

**Comment by jaemk** [comment]
Yes, an S3 backend would be great!

**Comment by bochaco** [comment]
Hi @jaemk , excellent!

I'm also trying to separate the main ReleaseList and Update logic from the backends, so backends return a list of releases which then are used to either lit of update. I'll be sending the PR as soon as I have something functional so we can discuss on it as it'll be easier.

Also, I'm planning to define some convention to realise the assets' version from the filenames (ince there are no tags in S3 as in GH), e.g. I'll be parsing the filenames as `<asset name>-<semver>-<platform/target>.<extension>`.

**Comment by bochaco** [comment]
@jaemk PR #35 is ready for review, please take a look and let me know what you think. 
I was trying to get even more re-usability in place with the introduction of the traits I created in `update.rs`, but apparently it's not possible to have fields in Traits as per what I found on the web which is what I'd need for it. The following seems to be the corresponding discussion and RFC respectively:
https://internals.rust-lang.org/t/fields-in-traits/6933
https://github.com/nikomatsakis/fields-in-traits-rfc/blob/master/0000-fields-in-traits.md
