### ISSUE TITLE
Add crate "features" to disable some parts?

### ISSUE THREAD

**Issue by nbigaouette** [jaemk/self_update#39]
I use `self_update` for one of my project (thanks!) with releases being uploaded to GitHub as zip files.

GitHub Actions has everything required to build the project, but I would like to make sure my project can be built directly by users without having to install anything else than rust, specially on Windows.

As such, I chose an archive format to use in my releases that I know has a 100% rust compression code. Unfortunately, because `self_update` depends on others, they are still pulled even though I don't need them.

The problem comes from Windows where `self_update` depends on `zip`: https://github.com/jaemk/self_update/blob/ef85a3451f27965f9d1f60eb080cbb348efd0149/Cargo.toml#L22

`cargo-tree` reveals the dependency tree:

```
> cargo tree
[...]
├── self_update v0.11.1
[...]
│   └── zip v0.5.4
│       ├── bzip2 v0.3.3
│       │   ├── bzip2-sys v0.1.7
│       │   │   └── libc v0.2.66 (*)
│       │   │   [build-dependencies]
│       │   │   └── cc v1.0.50
│       │   └── libc v0.2.66 (*)
│       ├── crc32fast v1.2.0 (*)
│       ├── flate2 v1.0.13 (*)
│       ├── podio v0.1.6
│       └── time v0.1.42 (*)
```

Because `zip` depends on `bzip2` and then `bzip2-sys`, cargo will attempt to build bzip2 on Windows. Because I don't have Visual Studio installed in my VM, I get the following error:
```
error: failed to run custom build command for `bzip2-sys v0.1.7`

Caused by:
  process didn't exit successfully: `C:\cargo_target\debug\build\bzip2-sys-85bed80a0555d110\build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-D_FILE_OFFS
ET_BITS=64" "-DBZ_NO_STDIO" "-o" "C:\\cargo_target\\debug\\build\\bzip2-sys-a067f608dc4f1377\\out\\lib\\bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c"

--- stderr


error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)



warning: build failed, waiting for other jobs to finish...
error: build failed
```
which is unfortunate since I don't even use bzip2.

Looking at `zip` I see that it has some features:
https://github.com/mvdnes/zip-rs/blob/master/Cargo.toml#L27-L31

I was able to add a feature to `self_update` to disable `zip`'s `bzip2` feature and thus allow having a 100% rust compilation 🎉 . See updated `cargo tree`:

```
> cargo tree
[...]
│   └── zip v0.5.4
│       ├── crc32fast v1.2.0 (*)
│       ├── flate2 v1.0.13 (*)
│       ├── podio v0.1.6
│       └── time v0.1.42 (*)
```

I think it could be interesting for others. It would reduce the amount of dependencies used and speed up compilation process.

Would you be interested in a PR?

**Comment by jaemk** [comment]
Yikes! Yes, a PR would be great!

**Comment by nbigaouette** [comment]
I've opened #40 which hides all format/compression behind flags, not just the one I needed to fix my compilation issue.
