### ISSUE TITLE
Use rustls for reqwest (default or provide feature flag)

### ISSUE THREAD

**Issue by joshuef** [jaemk/self_update#42]
I've [a wee branch on the go](https://github.com/joshuef/self_update/tree/use_rust_tls), using [`rustls`](https://github.com/ctz/rustls) to avoid libssl issues on linux (which `reqwest` uses by default).

I'm not sure if it's desirable to use this as the default tls implementation for `self_update` (it mayyy be [better than using openssl performance wise](https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html), or [in terms of security](https://hn.algolia.com/?q=openssl)...

Is there any desire for a PR to enable `rustls` via feature flag? Or even as default? Happy to update my branch and PR that if desirable 👍 

Thanks for all the work so far!

**Comment by dirvine** [comment]
Brilliant, this will help us and many more folk who have libssl issues. Nice one.

**Comment by jaemk** [comment]
A PR would be great! I think an optional feature for now would be best

**Comment by joshuef** [comment]
https://github.com/jaemk/self_update/pull/43 Added. 

Let me know if any changes are desirable 👍  will get on them asap.

**Comment by jaemk** [comment]
added in #43
