### ISSUE TITLE
Allow for usage for Enterprise Github

### ISSUE THREAD

**Issue by beckler** [jaemk/self_update#48]
I'm looking to leverage this package for an internal app at my employer, but we're required to use an enterprise Github instance.

Right now, it looks like the Github backend is hardcoded to `api.github.com`.
I think it would be rather easy to have a method that allows overriding that value.
There are a few small URL differences in enterprise, but would you be open to this if I were to create a PR for it?

**Comment by jaemk** [comment]
Yes a PR would be great!

**Comment by SirWindfield** [comment]
Not sure if #54 completely implements it.

**Comment by jaemk** [comment]
released in 0.18.0
