### ISSUE TITLE
DigitalOcean Spaces backend

### ISSUE THREAD

**Issue by zeenix** [jaemk/self_update#56]
This shouldn't be a lot of work, just some minor diffs to S3, I think? I can take a stab at it but would like to know if you'd want a separate backend of should it be just a configuration of S3 backend?

**Comment by zeenix** [comment]
I modified the hardcoded URL in S3 backend to point to digitalocean spaces and it worked so I don't think there is need for a separate backend. I'll just add a parameter to control the endpoint.

**Comment by jaemk** [comment]
released in 0.20.0
