### ISSUE TITLE
Allow specifying the version to update to

### ISSUE THREAD

**Issue by vitiral** [jaemk/self_update#6]
the [Builder](https://docs.rs/self_update/0.2.5/self_update/backends/github/struct.Builder.html#method.target) object should have a method `version` that allows you to specify the version to update to.

Proposed API:
```
/// update to the specified version.
fn version(&mut self, version: Version)
```

Usecase: I want to add an `update` command to my application where the user can specify the version to update to.

This is also great for testing. It lets me test out upgrading and downgrading dynamically.

**Comment by jaemk** [comment]
I'm on vacation currently, but I'll get to this and the other issues later this week!

**Comment by jaemk** [comment]
A builder method `target_version_tag` has been added in `0.4.0`. This lets you specify a tag name to search for a release via the github api: `/repos/:owner/:repo/releases/tags/:tag`. if `target_version_tag` isn't provided, `github::Update` will default to the latest available release. Most internal functionality has also been exposed in the [`github`](https://docs.rs/self_update/0.4.0/self_update/backends/github/index.html) backend for fetching available releases and working with `Release`s and their `ReleaseAsset`s.
