### ISSUE TITLE
Using unmaintained crate hyper-old-types

### ISSUE THREAD

**Issue by jplatte** [jaemk/self_update#63]
The `hyper-old-types` crate is rather old by now and pulls in various old versions of other crates.

I'd recommend you either drop the usage of typed headers entirely (AFAICT the only use of `hyper-old-types` in this crate is two headers) or update the headers crate which is the continuation of hyper's previous typed-headers API to work for your needs (https://github.com/hyperium/headers/issues/76).

**Comment by jaemk** [comment]
Where in the world did these old types go? `use hyper_old_types::header::{LinkValue, RelationType};` Looks like they were in hyper up until around v0.11 . Maybe it was the transition to the `http` crate, which seems like it doesn't include structure link headers 🤔

**Comment by jplatte** [comment]
AFAIK it was a decision independent of moving to the http crate to drop typed headers as many people were looking for a simpler way of handling headers and they were determined to not pull their weight as a built-in feature or sth. like that.
