### ISSUE TITLE
Support S3 dualstack

### ISSUE THREAD

**Issue by niklasf** [jaemk/self_update#91]
It would be nice to be able to use backend endpoints like `s3.dualstack.us-west-2.amazonaws.com` for IPv6 support.

Which option is best?
* Do nothing. People can set region `dualstack.us-west-2`
* Just use dualstack by default
* Add new endpoint type to enum

**Comment by jaemk** [comment]
I think option 1 is the best short term solution. I’m not sure we should use dualstack by default. I’m open to a PR adding a flag to the s3 config to signal that we should add “dualstack” to the hostname generated here https://github.com/jaemk/self_update/blob/79c471d4afb1b8c1a50f9ad1dc407defc22c9ff2/src/backends/s3.rs#L511
