### ISSUE TITLE
Is there a `.with_url()` method missing in `UpdateBuilder`?

### ISSUE THREAD

**Issue by avsaase** [jaemk/self_update#97]
I'm struggling to adapt the provided example for a GitHub Enterprise environment. There is a `.with_url()` method in `ReleaseListBuilder` to get a list of my releases but I don't see the corresponding method in `UpdateBuilder` to actually perform the update. Was this overlooked in https://github.com/jaemk/self_update/pull/54?

**Comment by jaemk** [comment]
Yes, seems like it was overlooked. Feel free to open a PR!

**Comment by avsaase** [comment]
See the PR above.

**Comment by jaemk** [comment]
Thanks! Released in 0.34.0
